### ISSUE TITLE
Player crashes with some music files

### ISSUE THREAD

**Issue by knochenhans** [HippoPlayer/HippoPlayer#121]
The current version segfaults with some music files. What’s the best way to help you with this, should I just attach the respective files? :)

**Comment by emoon** [comment]
Attach the files would be great :)

**Comment by knochenhans** [comment]
Ok, seems all of the files I ran into crashes so far are ymst files, I attached a specimen (had to zip it as git doesn’t seem to like the filetype)!
[buffalobill.ymst.zip](https://github.com/emoon/HippoPlayer/files/4943482/buffalobill.ymst.zip)

**Comment by knochenhans** [comment]
Found another file type that crashes (.mon): 
[chinese chess (ingame).mon.zip](https://github.com/emoon/HippoPlayer/files/4943509/chinese.chess.ingame.mon.zip)

**Comment by emoon** [comment]
Thanks! I will take a look

**Comment by emoon** [comment]
Seems that both of these files make something go bad inside UADE. I will have to investigate more deeper as other files for UADE works.

**Comment by emoon** [comment]
Built the gitversion of UADE and tested with their player and seems to work on the files that breaks in Hippo. Might be that it has been fixed in a later version so will have to try to upgrade it.

I have some local changes in UADE which makes merging some work (some specific code to make it work on Windows) but it should all be doable.

**Comment by knochenhans** [comment]
Found another problematic file, this one throws lots of uade errors, making the player crash eventually
[Lightyear.SymMOD.zip](https://github.com/emoon/HippoPlayer/files/5003309/Lightyear.SymMOD.zip)

**Comment by emoon** [comment]
Thanks! I will try to take look this week.

**Comment by emoon** [comment]
I looked into the Lightyears file. The format of the file is `Symphonie` and UADE doesn't support that format, but because it's name `.mod` it thinks it can play it. I will have to look closer at it, but current that format isn't supported right now

**Comment by knochenhans** [comment]
Another one, this one makes the player crash with:

```
terminate called after throwing an instance of 'openmpt::exception'
  what():  error loading file
```
[MeloDance.zip](https://github.com/emoon/HippoPlayer/files/5008241/MeloDance.zip)

**Comment by emoon** [comment]
Thanks! I have investigated this new file, but I'm unsure what format it is. First the file is PowerPacked, but openmpt will unpack it bun then it doesn't know what the the format actually is. 

Do you know any player that can play this file?

**Comment by knochenhans** [comment]
Plays fine in DeliPlayer 2.50, it’s identified as a MED file there.

**Comment by emoon** [comment]
Thanks! openmpt supports MED so it might actually be a bug in openmpt then

**Comment by emoon** [comment]
Some fixes for the first files in 0.1.5 https://github.com/emoon/HippoPlayer/releases/tag/0.1.5

**Comment by sagamusix** [comment]
I had a look at MeloDance.zip and I was able to identify an issue in OpenMPT's PP20 depacker. It has been fixed upstream.

**Comment by emoon** [comment]
I have upgraded to `libopenmpt 0.5.4` in `hippo 0.1.20` so this issue should be solved now (and verified it locally) I will close this issue for now, but open it again if it still doesn't work

**Comment by knochenhans** [comment]
Here’s another file that crashes the player. First double click on the file unpacks 5 tracks, second double click (on the first track) crashes the play with the following error:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:236:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
/usr/bin/hippoplayer: line 3: 82732 Aborted                 (core dumped) ./hippo_player
```
[paradroid 90.sc68.zip](https://github.com/HippoPlayer/HippoPlayer/files/6409300/paradroid.90.sc68.zip)

**Comment by emoon** [comment]
Managed to repro here. Log

```
12:14:25.217 [sc68 0.0.1          ] ERROR Failed to process /home/emoon/Music/paradroid 90.sc68
12:14:44.979 [openmpt 0.0.2       ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.979 [stsound 0.0.1       ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.979 [flac 0.0.1          ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.979 [SID 1.0.0           ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.979 [oggvorbis 0.0.1     ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.979 [Game Music Emu 0.0.1] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68 (Wrong file type for this emulator)
12:14:44.979 [VGM 0.0.1           ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.979 [Hively 0.0.1        ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.980 [mp3 0.0.1           ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.980 [wavpack 0.0.1       ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.980 [ayfly 0.0.1         ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.988 [adplug 1.0.0        ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.988 [tfmx 1.0.2          ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.988 [mdx 0.0.1           ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.988 [sc68 0.0.1          ] INFO  Supported: /home/emoon/Music/paradroid 90.sc68
12:14:44.988 [sc68 0.0.1          ] ERROR Failed to process /home/emoon/Music/paradroid 90.sc68
12:14:44.989 [asap 0.0.1          ] DEBUG Unsupported: /home/emoon/Music/paradroid 90.sc68
12:14:44.989 [core                ] WARN  No playback plugin found for: /home/emoon/Music/paradroid 90.sc68|0
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:236:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

**Comment by emoon** [comment]
So it seems that `sc68` is unable to play the file, then hippo (for whatever reason) thinks it can next time around. Do you know if this file works in some other player?

**Comment by knochenhans** [comment]
DeliPlayer 2 (which is my usual benchmark in this regard) at least is not able to recognize and play it.

**Comment by emoon** [comment]
I see. It's kinda weird because it first figures out all the sub songs and then crashes. I will have to debug this one. Thanks for finding all of these crashing cases, helps me fix stuff :)

**Comment by knochenhans** [comment]
Glad to help, I downloaded the whole Modland archive at one point containing roughly 450,000 files, so I have plenty of obscure file formats (and probably many broken files) I regularly throw at Hippo ^^

**Comment by emoon** [comment]
Nice :) Yeah I have everything locally as well, but I guess I haven't tried to many bad files yet :D
